http://localhost:3000/cursos

###

GET http://localhost:3000/cursos/1

###

POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json

{
    "nome": "Java"
}

###

PUT http://localhost:3000/cursos/2 HTTP/1.1
content-type: application/json

{
    "nome": "Java OO"
}

###

DELETE http://localhost:3000/cursos/2
